config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :limits do
  resources :expenses
  end

  get 'expenses/index'
  get '/expenses/:id/log', to: 'expenses#log', as: "log"
  get 'overview/index'
  get 'limits/:id', to: 'expenses#index', as: "expenses"

  root to: 'overview#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  skip_before_action :authorize, except: [:show, :new, :destroy]
  def index
    @overview = Expense.where("date > ?", Date.current.beginning_of_month).sum(:value)
	  @limits = Limit.order(expireDate: :desc).where( "expireDate > ?", Date.current).all
	  @expenses = Expense.all
  end

  def show
  end
end

app/helpers/overview_helper.rb
module OverviewHelper
end

app/views/overview/index.html.erb
<h1>Overview</h1>


<p>
  <strong>Expenses this month:</strong>
  <%= @overview %>
  
</p>

<p>
<h2>Current Limits:</h1>
<table>
  <thead>
    <tr>
      <th>Expiredate</th>
      <th>Limit</th>
      <th>Expenses</th>
      <th>Left</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @limits.each do |limit| %>
      <tr>
        <td><%= limit.expireDate %></td>
        <td><%= limit.limit %></td>
        <td><%= @expenses.where("date > ? AND date < ?", limit.created_at,limit.expireDate).sum(:value)%></td>
        <td><%= limit.limit - @expenses.where("date > ? AND date < ?", limit.created_at,limit.expireDate).sum(:value)%></td>
        <td><%= link_to 'Show', limit_expenses_path(limit) %></td>
        <td><%= link_to 'Edit', edit_limit_path(limit) %></td>
        <td><%= link_to 'Destroy', limit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</p>

<h3>
<%= link_to 'Manage your Limts and Expenses', limits_path, id: 'showLimits'  %>

</h3>

<p>
</p>

app/views/overview/show.html.erb
<h1>Overview</h1>

<p>
  <strong>Today:</strong>
  <%= Date.current() %>
</p>

<p>
  <strong>Expenses this month:</strong>
  <%= @overview %>
</p>

<p>
  <strong>Limit this month:</strong>
  <%= @limit %>
</p>

<p>
  <strong>Balance:</strong>
  <%= %>
</p>

<%= link_to 'Show past months', limit_path(0) %>

<%= link_to 'Back', expenses_path %>