config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :limits do
  resources :expenses
  end

  get 'expenses/index'
  get '/expenses/:id/log', to: 'expenses#log', as: "log"
  get 'overview/index'
  get 'limits/:id', to: 'expenses#index', as: "expenses"

  root to: 'overview#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/limit.rb
class Limit < ApplicationRecord
	has_many :expenses
end

app/controllers/limit_controller.rb
class LimitController < ApplicationController

  before_action :set_limit, only: [:edit, :update, :destroy]

  # GET /limit
  def index
    @limit = Limit.all  ## @limit change to @limits (Plural)
  end

  # GET /limit/0
  def show
	@limit = Limit.all
  end

  # GET /expenses/new
  def new
    @limit = Limit.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @limit = Limit.new(limit_params)

    respond_to do |format|
      if @limit.save
        format.html { redirect_to @limit, notice: 'Limit was successfully created.' }
        format.json { render :show, status: :created, location: @limit }
      else
        format.html { render :new }
        format.json { render json: @limit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @limit.update(limit_params)
        format.html { redirect_to @limit, notice: 'Limit was successfully updated.' }
        format.json { render :show, status: :ok, location: @limit }
      else
        format.html { render :edit }
        format.json { render json: @limit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @limit.destroy
    respond_to do |format|
      format.html { redirect_to limit_url, notice: 'Limit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_limit
      @limit = Limit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def limit_params
      params.require(:limit, :expireDate).permit( :expenses)
    end

end

app/controllers/limits_controller.rb
class LimitsController < ApplicationController
  before_action :set_limit, only: [:show, :edit, :update, :destroy, :newExpense, :createExpense]

  def newExpense
	  @expense = @limit.expenses.build()
  end

  # GET /limits
  # GET /limits.json
  def index
    @limits = Limit.order(expireDate: :desc)
	  @expenses = Expense.all
  end

  # GET /limits/1
  # GET /limits/1.json
  def show
    @expenses = @limit.expenses
  end

  # GET /limits/new
  def new
    @limit = Limit.new
  end

  # GET /limits/1/edit
  def edit
  end

  # POST /limits
  # POST /limits.json
  def create
    @limit = Limit.new(limit_params)
    respond_to do |format|
      if @limit.save
        format.html { redirect_to limit_expenses_path(@limit), notice: 'Limit was successfully created.' }
        format.json { render :show, status: :created, location: @limit }
      else
        format.html { render :new }
        format.json { render json: @limit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /limits/1
  # PATCH/PUT /limits/1.json
  def update
    respond_to do |format|
      if @limit.update(limit_params)
        format.html { redirect_to limit_expenses_path(@limit), notice: 'Limit was successfully updated.' }
        format.json { render :show, status: :ok, location: @limit }
      else
        format.html { render :edit }
        format.json { render json: @limit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /limits/1
  # DELETE /limits/1.json
  def destroy
    @limit.destroy
    respond_to do |format|
      format.html { redirect_to limits_url, notice: 'Limit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_limit
      @limit = Limit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def limit_params
      params.require(:limit).permit(:expireDate, :limit)
    end

	 # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:store, :description, :date, :value)
    end

end

app/helpers/limit_helper.rb
module LimitHelper
end

app/helpers/limits_helper.rb
module LimitsHelper
end

app/views/limit/_form.html.erb
<%= form_for(limit_index_url) do |f| %>
  <% if limit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(limit.errors.count, "error") %> prohibited this limit from being saved:</h2>

      <ul>
      <% limit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expireDate %>
    <%= f.date_select :expireDate %>
  </div>

  <div class="field">
    <%= f.label :limit %>
    <%= f.text_field :limit %>
  </div>

  <div class="field">
    <%= f.label :expanses %>
    <%= @expanses %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/limit/edit.html.erb
<h1>Editing Limit</h1>

<%= render 'form', limit: @limit %>

<%= link_to 'Show', @limit %> |
<%= link_to 'Back', limit_path %>

app/views/limit/index.html.erb
<h1>Limits</h1>

<%= link_to 'New Limit', new_limit_path %>

<table>
  <thead>
    <tr>
      <th>month</th>
      <th>limit</th>
      <th>expenses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @limit.each do |limit| %>
      <tr>
        <td><%= limit.expireDate %></td>
        <td><%= limit.limit %></td>
        <td><%= limit.expenses %></td>
        <td><%= link_to 'Show', limit %></td>
        <td><%= link_to 'Edit', edit_limit_path(limit) %></td>
        <td><%= link_to 'Destroy', limit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><h3><%= link_to 'Get an overview', overview_index_path %></h3></p>

app/views/limit/new.html.erb
<h1>New Limit</h1>

<%= render 'form', limit: @limit %>

<%= link_to 'Back', limit_index_path %>

app/views/limit/show.html.erb
<h1>Show Entry</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Expire Date:</strong>
  <%= @limit.expireDate %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @limit.limit %>
</p>

<p>
  <strong>Expenses:</strong>
  <%= @expense.value %>
</p>

<%= link_to 'Edit', edit_limit_path(@limit) %> |
<%= link_to 'Back', limit_path %>