config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :limits do
  resources :expenses
  end

  get 'expenses/index'
  get '/expenses/:id/log', to: 'expenses#log', as: "log"
  get 'overview/index'
  get 'limits/:id', to: 'expenses#index', as: "expenses"

  root to: 'overview#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy, :log]

  def log
    @expense.value = 0
    respond_to do |format|
      if @expense.save
        format.html { redirect_to limit_expenses_path(@expense.limit_id), notice: "Expense #{@expense.store} was reset." }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { redirect_to @expense, notice: "Expense #{@expense.store} could not reset." }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /expenses
  # GET /expenses.json
  def index
    @limit = Limit.find(params[:limit_id])
	  @expenses = @limit.expenses
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @limit = Limit.find(params[:limit_id])
	  @expense = @limit.expenses.build
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @limit = Limit.find(params[:limit_id])
	  @expense = @limit.expenses.create(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to limit_expenses_path(@limit), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to limit_expenses_path(@expense.limit_id), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
	@limit=Limit.find(params[:limit_id])
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to limit_expenses_path(@limit), notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:store, :description, :date, :value)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= form_for @expense, url: limit_expense_path(@expense.limit, @expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store %>
    <%= f.text_field :store %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', limit_expense_path(@expense) %> |
<%= link_to 'Back', limit_expenses_path(@expense.limit_id) %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

  <h1>
	Your Limit:
	</h1>
  <p> <strong>Expiredate:</strong>  <%= @limit.expireDate %></p>

  <p> <strong>Limit:</strong> <%= @limit.limit %></p>

  <%= link_to 'Edit', edit_limit_path(@limit) %> |
  <%= link_to 'Destroy', @limit, method: :delete, data: { confirm: 'Are you sure?' } %>

<p>
  <h2>
	Expenses:
	</h2>
</p>

<%= link_to 'New Expense', new_limit_expense_path(@limit) %>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>Description</th>
      <th>Date</th>
      <th>Value</th>
      <th>Log</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.store %></td>
        <td><%= expense.description %></td>
        <td><%= expense.date %></td>
        <td><%= expense.value %></td>
        <td><%= form_tag log_path(expense) , method: :get do | form |%>
            <%= button_tag "Reset value", id: "button-#{expense.id}"%>
            <% end %></td>
        <td><%= link_to 'Show', limit_expense_path(expense.limit_id, expense) %></td>
        <td><%= link_to 'Edit', edit_limit_expense_path(expense.limit_id, expense) %></td>
        <td><%= link_to 'Destroy', limit_expense_path(expense.limit_id, expense), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
<h3>
<%= link_to 'Get an overview', overview_index_path %>
</h3>
</p>

app/views/expenses/new.html.erb
<h1>New Expense</h1>
<%= form_for @expense, url: limit_expenses_path(@expense.limit) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store %>
    <%= f.text_field :store %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', limit_expenses_path(@expense.limit)%>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= @expense.store %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Value:</strong>
  <%= @expense.value %>
</p>

<%= link_to 'Edit', edit_limit_expense_path(@expense) %> |
<%= link_to 'Back', limit_expenses_path(@expense.limit) %>